dist: xenial

language: node_js

node_js:
  - "8"

stages:
  - lint

jobs:
  include:
    - stage: lint
      name: Terraform Lint/Format Verification
      install:
        - make terraform/install
        - make terraform-docs/install
      script:
        - make docs/lint